apiVersion: v1
kind: Service
metadata:
  name: agrioxygen-service
  labels:
    app: agrioxygen
spec:
  type: NodePort
  selector:
    app: agrioxygen
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080